#!/usr/bin/env bash

set -eu

echo "Generate coverage and test report"
python3 setup.py develop && pytest --cov=genie_pkg --cov-report=xml --junitxml=pytest-report.xml

echo "Scanning now..."
# SONAR_CLOUD_TOKEN should be added in circleci
if [ 'master' = $CIRCLE_BRANCH ] 
then
    sonar-scanner -X -Dsonar.login="$SONAR_CLOUD_TOKEN"
else
    PR_KEY=$(echo "$CIRCLE_BRANCH" | cut -f7 -d "/")
    sonar-scanner -X -Dsonar.login="$SONAR_CLOUD_TOKEN" \
                    -Dsonar.pullrequest.branch="$CIRCLE_BRANCH" \
                    -Dsonar.pullrequest.key="$PR_KEY" \
                    -Dsonar.pullrequest.base=master \
                    -Dsonar.pullrequest.provider=GitHub \
                    -Dsonar.pullrequest.github.repository=mkeshav/data-genie
fi
