#!/usr/bin/env bash

set -eu
echo -e " password = $PYPI_API_TOKEN" >> ~/.pypirc

# Repo by default on twine is pypi.org, $PYPI_API_TOKEN should be set in circle.
echo "Building...."
python3 setup.py sdist bdist_wheel
echo "Uploading...."
python3 -m twine upload --repository data-genie dist/*
