version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.2

    working_directory: ~/data-genie

    environment:
      TERM: dumb
    
    steps:
      - checkout
# Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install requirements.txt
      - save_cache:
          paths:
            - ./.local
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            
      - run:
          name: Run tests
          command: |
            pytest --cov=genie_pkg --cov-report=html
      